name: startline

services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:733e736
    platform: linux/amd64
    ports:
      - '8080:8080'
      - '5001:5001'
    volumes:
      - ./.data/libsql:/var/lib/sqld

  redis:
    image: redis:7.4.0
    ports:
      - '6379:6379'

  serverless-redis-http:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:0.0.10
    environment:
      SRH_MODE: env
      SRH_TOKEN: 'my-redis-rest-token'
      SRH_CONNECTION_STRING: 'redis://redis:6379'
